import type { PricingPlan } from "@/types/pricingType";

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "Miễn phí",
    period: "7 ngày dùng thử",
    description: "Dành cho người mới bắt đầu muốn trải nghiệm các tính năng cơ bản  ",
    headerColor: "bg-green-500/10 dark:bg-green-500/5",
    features: [
      { text: "100 tin nhắn/ngày", included: true },
      { text: "Kết nối Facebook Fanpage", included: true },
      { text: "Tạo sản phẩm", included: true },
      { text: "Tự động trả lời tin nhắn", included: true },
      { text: "Upsale / Cross-sale cơ bản", included: true },
      { text: "Huấn luyện AI bằng hội thoại", included: true },
      { text: "Hỗ trợ kỹ thuật email", included: true },
      { text: "Cá nhân hóa câu trả lời", included: false },
      { text: "Upsale nâng cao theo hành vi", included: false },
      { text: "Chốt đơn tự động", included: false },
      { text: "Báo cáo hàng tuần", included: false },
      { text: "Hỗ trợ Live Chat", included: false },
      { text: "Tích hợp chatbot Website", included: false },
      { text: "Tích hợp đa nền tảng (FB, Zalo, IG...)", included: false },
      { text: "Báo cáo theo thời gian thực", included: false },
      { text: "Huấn luyện AI bằng NLP", included: false },
      { text: "Tư vấn chiến lược riêng", included: false },
      { text: "Tùy chỉnh tính năng sâu", included: false },
    ],
    ctaText: "Dùng thử miễn phí",
    ctaLink: "signin",
    ctaStyle: "outline",
  },
  {
    id: "essentials",
    name: "Essentials",
    price: "599k",
    period: "Theo tháng",
    description: "Gói cơ bản với đầy đủ tính năng thiết yếu cho doanh nghiệp nhỏ ",
    headerColor: "bg-blue-500/10 dark:bg-blue-500/5",
    features: [
      { text: "500 tin nhắn/ngày", included: true },
      { text: "Kết nối Facebook Fanpage", included: true },
      { text: "Tạo sản phẩm", included: true },
      { text: "Tự động trả lời tin nhắn", included: true },
      { text: "Upsale / Cross-sale cơ bản", included: true },
      { text: "Huấn luyện AI bằng hội thoại", included: true },
      { text: "Hỗ trợ kỹ thuật email", included: true },
      { text: "Cá nhân hóa câu trả lời", included: true },
      { text: "Upsale nâng cao theo hành vi", included: true },
      { text: "Chốt đơn tự động", included: true },
      { text: "Báo cáo hàng tuần", included: true },
      { text: "Hỗ trợ Live Chat", included: true },
      { text: "Tích hợp chatbot Website", included: false },
      { text: "Tích hợp đa nền tảng (FB, Zalo, IG...)", included: false },
      { text: "Báo cáo theo thời gian thực", included: false },
      { text: "Huấn luyện AI bằng NLP", included: false },
      { text: "Tư vấn chiến lược riêng", included: false },
      { text: "Tùy chỉnh tính năng sâu", included: false },
    ],
    ctaText: "Chọn gói này",
    ctaLink: "signin",
    ctaStyle: "outline",
  },
  {
    id: "elite",
    name: "Elite",
    price: "799k",
    period: "Theo tháng",
    description: "Gói nâng cao với tích hợp chatbot và nhiều tính năng mạnh mẽ",
    headerColor: "bg-purple-500",
    featured: true,
    features: [
      { text: "1000 tin nhắn/ngày", included: true },
      { text: "Kết nối Facebook Fanpage", included: true },
      { text: "Tạo sản phẩm", included: true },
      { text: "Tự động trả lời tin nhắn", included: true },
      { text: "Upsale / Cross-sale cơ bản", included: true },
      { text: "Huấn luyện AI bằng hội thoại", included: true },
      { text: "Hỗ trợ kỹ thuật email", included: true },
      { text: "Cá nhân hóa câu trả lời", included: true },
      { text: "Upsale nâng cao theo hành vi", included: true },
      { text: "Chốt đơn tự động", included: true },
      { text: "Báo cáo hàng tuần", included: true },
      { text: "Hỗ trợ Live Chat", included: true },
      { text: "Tích hợp chatbot Website", included: true },
      { text: "Tích hợp đa nền tảng (FB, Zalo, IG...)", included: false },
      { text: "Báo cáo theo thời gian thực", included: false },
      { text: "Huấn luyện AI bằng NLP", included: false },
      { text: "Tư vấn chiến lược riêng", included: false },
      { text: "Tùy chỉnh tính năng sâu", included: false },
    ],
    ctaText: "Chọn gói này",
    ctaLink: "signin",
    ctaStyle: "outline",
  },
  {
    id: "prestige",
    name: "Prestige",
    price: "999k",
    period: "Theo tháng",
    description: "Gói cao cấp với đầy đủ tính năng và hỗ trợ đa nền tảng",
    headerColor: "bg-orange-500/10 dark:bg-orange-500/5",
    features: [
      { text: "Không giới hạn tin nhắn", included: true },
      { text: "Kết nối Facebook Fanpage", included: true },
      { text: "Tạo sản phẩm", included: true },
      { text: "Tự động trả lời tin nhắn", included: true },
      { text: "Upsale / Cross-sale cơ bản", included: true },
      { text: "Huấn luyện AI bằng hội thoại", included: true },
      { text: "Hỗ trợ kỹ thuật email", included: true },
      { text: "Cá nhân hóa câu trả lời", included: true },
      { text: "Upsale nâng cao theo hành vi", included: true },
      { text: "Chốt đơn tự động", included: true },
      { text: "Báo cáo hàng tuần", included: true },
      { text: "Hỗ trợ Live Chat", included: true },
      { text: "Tích hợp chatbot Website", included: true },
      { text: "Tích hợp đa nền tảng (FB, Zalo, IG...)", included: true },
      { text: "Báo cáo theo thời gian thực", included: true },
      { text: "Huấn luyện AI bằng NLP", included: true },
      { text: "Tư vấn chiến lược riêng", included: true },
      { text: "Tùy chỉnh tính năng sâu", included: false },
    ],
    ctaText: "Chọn gói này",
    ctaLink: "signin",
    ctaStyle: "outline",
  },
  {
    id: "bespoke",
    name: "Bespoke",
    price: "Liên hệ",
    period: "Tùy chỉnh theo nhu cầu",
    description: "Giải pháp tùy chỉnh hoàn toàn theo yêu cầu riêng của doanh nghiệp",
    headerColor: "bg-gray-600",
    features: [
      { text: "Không giới hạn tin nhắn", included: true },
      { text: "Kết nối Facebook Fanpage", included: true },
      { text: "Tạo sản phẩm", included: true },
      { text: "Tự động trả lời tin nhắn", included: true },
      { text: "Upsale / Cross-sale cơ bản", included: true },
      { text: "Huấn luyện AI bằng hội thoại", included: true },
      { text: "Hỗ trợ kỹ thuật email", included: true },
      { text: "Cá nhân hóa câu trả lời", included: true },
      { text: "Upsale nâng cao theo hành vi", included: true },
      { text: "Chốt đơn tự động", included: true },
      { text: "Báo cáo hàng tuần", included: true },
      { text: "Hỗ trợ Live Chat", included: true },
      { text: "Tích hợp chatbot Website", included: true },
      { text: "Tích hợp đa nền tảng (FB, Zalo, IG...)", included: true },
      { text: "Báo cáo theo thời gian thực", included: true },
      { text: "Huấn luyện AI bằng NLP", included: true },
      { text: "Tư vấn chiến lược riêng", included: true },
      { text: "Tùy chỉnh tính năng sâu", included: true },
    ],
    ctaText: "Liên hệ tư vấn",
    ctaLink: "contact",
    ctaStyle: "outline",
  },
]
